<a href="https://colab.research.google.com/github/TunanshV/DL/blob/main/00_tensorflow_fundamentals_exercise_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [7]:
#a vector is a rank-1 tensor and it is like a list of numbers.It has one axis
vector= tf.constant([1,2,3,4])
vector.ndim


<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [28]:
#a scalar is a rank-0 tensor and it contains a single value and no axes
scaler= tf.constant(4)
scaler.shape
tf.rank(scaler)
tf.size(scaler)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [29]:
# a matrix or rank-2 tensor has two axes.We can set the dtype using aliases.
matrix= tf.constant([[1,2,3],
                     [4,5,6],
                     [7,8,9]],dtype=tf.float16)
matrix.shape
tf.size(matrix)
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [35]:
#creating a tensor
tensor= tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[10,11,12],
                      [13,14,15]]])
tensor.shape
tf.rank(tensor)
tf.size(tensor).numpy()


12

In [39]:
#creating two tensors containing random values between 0 and 1 with shape[5,300]
tensor_5= tf.random.uniform(minval=0,maxval=1,shape=(5,300))
tensor_6= tf.random.uniform(minval=0,maxval=1,shape=(5,300))
tensor_5,tensor_6

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7137722 , 0.5682577 , 0.48995173, ..., 0.698532  , 0.41530716,
         0.03724349],
        [0.9573169 , 0.683974  , 0.6878983 , ..., 0.9240624 , 0.7371949 ,
         0.65380275],
        [0.3937236 , 0.27419508, 0.3144101 , ..., 0.21759593, 0.16180694,
         0.17584848],
        [0.6079097 , 0.01292431, 0.75487685, ..., 0.9095659 , 0.403386  ,
         0.25664032],
        [0.3800596 , 0.31613255, 0.3142258 , ..., 0.27977347, 0.58511436,
         0.12036538]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.62466514, 0.59434736, 0.84485793, ..., 0.31635547, 0.4538108 ,
         0.24049306],
        [0.66818655, 0.7279763 , 0.66202915, ..., 0.8968564 , 0.8384441 ,
         0.00178802],
        [0.827266  , 0.9304174 , 0.7687652 , ..., 0.01306891, 0.3052523 ,
         0.5744549 ],
        [0.73021984, 0.5574758 , 0.13693106, ..., 0.09689617, 0.4381647 ,
         0.54614186],
        [0.89416

In [41]:
#Multiply the two matrices using matrix multiplication
tf.matmul(tensor_5,tf.transpose(tensor_6))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[62.66284 , 73.1556  , 70.633545, 66.7171  , 74.7276  ],
       [59.8123  , 67.740906, 70.72894 , 67.078865, 74.2408  ],
       [65.08165 , 72.40057 , 71.18701 , 70.55434 , 74.17134 ],
       [70.70337 , 77.729866, 78.66063 , 72.79042 , 80.96927 ],
       [65.22966 , 75.809616, 76.402725, 73.92375 , 80.60454 ]],
      dtype=float32)>

In [44]:
#Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor_5,tf.transpose(tensor_6),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[62.66284 , 73.1556  , 70.633545, 66.7171  , 74.7276  ],
       [59.8123  , 67.740906, 70.72894 , 67.078865, 74.2408  ],
       [65.08165 , 72.40057 , 71.18701 , 70.55434 , 74.17134 ],
       [70.70337 , 77.729866, 78.66063 , 72.79042 , 80.96927 ],
       [65.22966 , 75.809616, 76.402725, 73.92375 , 80.60454 ]],
      dtype=float32)>

In [47]:
#create a tensor with random values between 0 and 1 with shape [224,224,3]
tensor_6= tf.random.uniform(minval=0,maxval=1,shape=(224,224,3))
tensor_6


<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.3640343 , 0.5658885 , 0.8847954 ],
        [0.3796494 , 0.8182188 , 0.12649667],
        [0.24847889, 0.75822663, 0.50102377],
        ...,
        [0.7072307 , 0.8609998 , 0.0082736 ],
        [0.45533943, 0.21503198, 0.88382614],
        [0.59046066, 0.8967197 , 0.54907155]],

       [[0.28570628, 0.30150926, 0.29127872],
        [0.1716721 , 0.7223995 , 0.31483877],
        [0.30985773, 0.29281986, 0.45481265],
        ...,
        [0.56355953, 0.94686174, 0.17731333],
        [0.38282013, 0.58050656, 0.30144548],
        [0.30898285, 0.78468776, 0.649189  ]],

       [[0.93584573, 0.9085084 , 0.52413833],
        [0.52358127, 0.9590806 , 0.00311756],
        [0.9004077 , 0.9762747 , 0.54096985],
        ...,
        [0.00579548, 0.39201164, 0.42807555],
        [0.5057306 , 0.66900396, 0.06851351],
        [0.03052783, 0.23064387, 0.81697   ]],

       ...,

       [[0.36930883, 0.66202235, 0.682896  ],
        [0.79

In [50]:
#Find the min and max values of the tensor you created along the first axis.
tf.reduce_min(tensor_6).numpy()
tf.reduce_max(tensor_6).numpy()

0.9999951

In [51]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
random_values= tf.random.uniform(shape=(1,224,224,3))

In [52]:
random_values

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.7619742 , 0.61023235, 0.81687105],
         [0.15875173, 0.8664751 , 0.93234074],
         [0.6357801 , 0.7666447 , 0.08947754],
         ...,
         [0.26273346, 0.4354875 , 0.34259617],
         [0.04008472, 0.7298094 , 0.18792915],
         [0.69863117, 0.21169984, 0.10472047]],

        [[0.4056039 , 0.6504762 , 0.4091921 ],
         [0.5984125 , 0.42653394, 0.3518765 ],
         [0.20364308, 0.95550156, 0.01669371],
         ...,
         [0.8520869 , 0.31219673, 0.66480756],
         [0.50947976, 0.2947439 , 0.46815467],
         [0.5300673 , 0.01465213, 0.4862796 ]],

        [[0.8138521 , 0.33862388, 0.8198477 ],
         [0.60719573, 0.5124556 , 0.3173474 ],
         [0.92415273, 0.67972064, 0.46531284],
         ...,
         [0.7390405 , 0.8885721 , 0.15659845],
         [0.20935142, 0.15445876, 0.4203198 ],
         [0.4690534 , 0.9983901 , 0.9568938 ]],

        ...,

        [[0.9898654 , 0.43131042, 

In [54]:
squeezed_random_values=tf.squeeze(random_values)
squeezed_random_values

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7619742 , 0.61023235, 0.81687105],
        [0.15875173, 0.8664751 , 0.93234074],
        [0.6357801 , 0.7666447 , 0.08947754],
        ...,
        [0.26273346, 0.4354875 , 0.34259617],
        [0.04008472, 0.7298094 , 0.18792915],
        [0.69863117, 0.21169984, 0.10472047]],

       [[0.4056039 , 0.6504762 , 0.4091921 ],
        [0.5984125 , 0.42653394, 0.3518765 ],
        [0.20364308, 0.95550156, 0.01669371],
        ...,
        [0.8520869 , 0.31219673, 0.66480756],
        [0.50947976, 0.2947439 , 0.46815467],
        [0.5300673 , 0.01465213, 0.4862796 ]],

       [[0.8138521 , 0.33862388, 0.8198477 ],
        [0.60719573, 0.5124556 , 0.3173474 ],
        [0.92415273, 0.67972064, 0.46531284],
        ...,
        [0.7390405 , 0.8885721 , 0.15659845],
        [0.20935142, 0.15445876, 0.4203198 ],
        [0.4690534 , 0.9983901 , 0.9568938 ]],

       ...,

       [[0.9898654 , 0.43131042, 0.08581769],
        [0.72

In [68]:
#Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
random_8= tf.random.uniform(minval=1,maxval=10,shape=[10])
random_8

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.1214337, 1.3303323, 9.335588 , 7.6296825, 5.6383924, 7.117324 ,
       1.9448704, 3.835213 , 1.0281514, 7.06701  ], dtype=float32)>

In [69]:
random_8[tf.argmax(random_8)].numpy()

9.335588

In [70]:
tf.cast(random_8.numpy().tolist(),tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 1, 9, 7, 5, 7, 1, 3, 1, 7], dtype=int32)>

In [72]:

one_hot_encoder= tf.one_hot(tf.cast(random_8.numpy().tolist(),tf.int32),depth=tf.size(random_8).numpy())
one_hot_encoder

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>